# -*- coding: utf-8 -*-
"""Custom_Conway's_Game_of_Life.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k3Y_NiG69bCP9dRjChcGqCSGFhy8qSw9
"""

!pip install numpy matplotlib pillow

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

# Initialise the size of the grid
N = 50

# Initialize Minimum number of neighbors
min_neighbors = 1

# Initialize the Maximum number of neighbors
max_neighbors = 4

# Intialize the number of neighbors to reproduce
reproduce = 2

# Initialize a random grid
random_grid = np.random.randint(2, size=(N, N))


# initialize a square grid
square_grid = np.zeros((N, N))

for i in range(0, N):
    for j in range(0, N):
        if i == 2 or i == (N-3) or j == 2 or j == (N-3):
            square_grid[i, j] = 1
        else:
            square_grid[i, j] = 0

#intitialize a grid, filled when the index is even
evens_grid = np.zeros((N, N))

for i in range(0, N):
    for j in range(0, N):
        if i % 2 == 0 and j % 2 == 0:
            evens_grid[i, j] = 1
        else:
            evens_grid[i, j] = 0

custom_grid = [ [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
custom_grid = np.array(custom_grid)
N = 30

# IMPORTANT!! Set active grid to either: random_grid, square_grid, evens_grid, custom_grid
grid = custom_grid

def count_neighbors(grid, x, y):
    total = 0

    for i in range(-1, 2):
        for j in range(-1, 2):

            # Skip the center cell
            if i == 0 and j == 0:
                continue

            # Calculate the coordinates of the neighboring cell
            ni = x + i
            nj = y + j

            # Check if the neighboring cell is within the grid bounds
            if 0 <= ni < N and 0 <= nj < N:
                total += grid[ni, nj]

    return total

# Update the grid based on Game of Life rules
def update_grid(grid):
    new_grid = np.zeros((N, N))
    for i in range(N):
        for j in range(N):
            live_neighbors = count_neighbors(grid, i, j)
            # If cell is alive
            if grid[i, j] == 1:
                # If there is too many neighbors or not enough
                if live_neighbors <= min_neighbors or live_neighbors >= max_neighbors:
                    new_grid[i, j] = 0
                else:
                    new_grid[i, j] = 1

            # If cell has the exact amount to reproduce
            # Can change expression to <, > to get different results
            elif live_neighbors == reproduce:
                new_grid[i, j] = 1
    return new_grid

# Function to animate the grid
def animate(i):
    global grid
    grid = update_grid(grid)
    mat.set_data(grid)
    return [mat]


fig, ax = plt.subplots()
mat = ax.matshow(grid, cmap='binary')
plt.title('Conway\'s Game of Life')

# Display the first frame
print("First Frame")
plt.show()

ani = animation.FuncAnimation(fig, animate, frames=200, interval=100, blit=True)
ani.save('game_of_life.gif', writer='pillow', fps=10)
plt.show()